config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import newCV
from .views import myCv
from .views import qr
from .views import qaa
from .views import index
from .views import validate
from .views import downloadFile
from .views import pdf_report_create
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('pages.urls')),  # new
    # # path('cv/', newCV),
    path('myCV/', myCv),
    path('qr/', qr),
    path('qaa/', qaa),
    path('downloadFile/', downloadFile),
    # path("",include("sendemail.urls"))
    path('cv/', index, name = 'index'), #index= padina care se completeaza
    path('cv/validate', validate, name = 'validate'),
    path('cv/validate/pdf', pdf_report_create, name = 'pdf_report_create')
]

pages/urls.py
# pages/urls.py
from django.urls import path
from .views import newCV
from .views import myCv
from .views import qr
from .views import qaa

from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('cv/',newCV ),
     path('myCV/', myCv),
     path('qr/', qr),
     path('qaa/', qaa),
    
]

pages/views.py
from django.shortcuts import render
from django import forms
# Create your views here.
# pages/views.py
from django.views.generic import TemplateView
from django.http import HttpResponse
from django.shortcuts import render
import qrcode
import qrcode.image.svg
from io import BytesIO
from django.core import mail
from django.core.mail import send_mail
from django.core import mail
import smtplib
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from django.shortcuts import render
from django.core.mail import send_mail
from django.conf import settings
from django.core.mail import EmailMultiAlternatives
from django.core.mail import EmailMessage
from email.message import EmailMessage
from django.http import HttpResponse
from django.shortcuts import render
from .data import *
import html
from django.utils.html import escape
import mimetypes
import os
from wsgiref.util import setup_testing_defaults
from wsgiref.simple_server import make_server
from wsgiref.util import FileWrapper
from django.http import StreamingHttpResponse
import pdfkit as pdf

send_mail(
    subject = 'Test Mail',
    message = 'Maria V',
    from_email = 'maria.vasilache02@gmail.com',
    recipient_list = ['maria.vasilache02@gmail.com',],
    fail_silently = False,
)

class EmailForm(forms.Form):
     recipient = forms.EmailField()
     message = forms.CharField(widget=forms.Textarea)


class HomePageView(TemplateView):
    template_name = 'home.html'

# def newCV(request):
#       #se preiau toate datele din interfata si se vor pune in baza de date;
#     return render(request, 'QR/newCV.html')  

# def myCv(request):
#      return render(request, 'QR/MyCV.html')  

def qr(request):
     return render(request, 'QR/QRcode.html')  

def qaa(request): 

# create a variable to keep track of the form
    messageSent = False
    recipient = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    server=smtplib.SMTP_SSL("smtp.gmail.com", 465)
    server.login("maria.vasilache02@gmail.com", "qgrqmaoreadfcszp")

    # check if form has been submitted
    if request.method == 'POST':

        form = EmailForm(request.POST)

        # check if data from the form is clean
        if form.is_valid():
            cd = form.cleaned_data
            subject = "CV-issue"
            message = cd['message']
            emm=cd['recipient']
            files = request.FILES.getlist('attach')
            #attach = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
           # server.sendmail("maria.vasilache02@gmail.com", ["maria.vasilache02@gmail.com", [cd['recipient']]], subject+"\n"+message) 
           # server.quit()
            files
            email = EmailMessage()

            email['Subject'] = subject
            email['From'] = emm
            email['To'] = 'maria.vasilache02@gmail.com'
            email.set_content("S-a primit o solicitare de la "+emm+"\n\n"+ "Mesajul transmis:\n "+message+"\n"+"\nATENTIE: Este posibil sa fie incarcate atasamenta!!")

            with open('D:\An3\IS\P1\cv.pdf', 'rb') as content_file:
                
                content = content_file.read()
                email.add_attachment(content, maintype='application', subtype='pdf', filename='cv.pdf')

            server.send_message(email)
            

            messageSent = True

    else:
        form = EmailForm()

    return render(request, 'QR/QandA.html', {

        'form': form,
        'messageSent': messageSent,

    })


def qr(request):
     context = {}
     if request.method == "POST":
          factory = qrcode.image.svg.SvgImage
          img = qrcode.make(request.POST.get("qr_text",""), image_factory=factory, box_size=20)
          stream = BytesIO()
          img.save(stream)
          context["svg"] = stream.getvalue().decode()

     return render(request, "QR/QRcode.html", context=context)



def getSkills():
    i = 0
    gotoshow = ""
    while i < len(yourSkills):
        skill = "<li><span class='main full'>" + yourSkills[i] + "</span></li>"
        i += 1
        gotoshow = gotoshow + skill
        if i == len(yourSkills):
            return html.unescape(gotoshow)

def getList(shema):
    i = 0
    gotoshow = ""
    while i < len(shema):
        skill = "<li>" + shema[i] + "</li>"
        i += 1
        gotoshow = gotoshow + skill
        if i == len(shema):
            return html.unescape(gotoshow)

def getListWithYear(shema, year):
    i = 0
    gotoshow = ""
    while i < len(shema):
        if year[i]:
           skill = "<li><span class='main'>" + shema[i] + "</span><span class='year'>" + year[i] + "</span></li>"
        else:
           skill = "<li><span class='main full'>" + shema[i] + "</span></li>"
        i += 1
        gotoshow = gotoshow + skill
        if i == len(shema):
            return html.unescape(gotoshow)

def getListWithLink(shema, link):
    i = 0
    gotoshow = ""
    while i < len(shema):
        if link[i]:
            skill = "<li><a target='_blank' href='" + link[i] + "'>" + shema[i] + "</a></li>"
        else:
            skill = "<li><a target='_blank'>" + shema[i] + "</a></li>"
        i += 1
        gotoshow = gotoshow + skill
        if i == len(shema):
            return html.unescape(gotoshow)

def getSocials(shema, link):
    i = 0
    gotoshow = ""
    while i < len(shema):
        if link[i]:
            skill = "<a class='social' target='_blank' href='" + link[i] + "'><i class='" + shema[i] + "'></i></a>"
            gotoshow = gotoshow + skill
        else:
            gotoshow = gotoshow
        i += 1
        if i == len(shema):
            return html.unescape(gotoshow)

def data():
    #sa le preia din baza de date
    return {
        'titleCV' : titleCV,
        'yourName' : yourName,
        'yourProfession' : yourProfession,
        'yourBio' : yourBio,
        'yourCountry' : yourCountry,
        'yourContact' : getSocials(socialContact, yourContact),
        'yourBirthday' : yourBirthday,
        'yourSkills' : getSkills(),
        'yourHobbies' : getList(yourHobbies),
        'yourCerts' : getList(yourCerts),
        'yourEdu' : getListWithYear(yourEdu, eduYear),
        'yourWork' : getListWithYear(yourWork, workYear),
        'yourProject' : getListWithLink(yourProject, projectLink),
        'yourExtras': getList(yourExtras),
        'footerText': footerText
        }

def newCV(request):
      #se preiau toate datele din interfata si se vor pune in baza de date;
    return render(request, 'QR/newCV.html')  
#validate
def myCv(request):
     return render(request, 'QR/MyCV.html',  data())  
#def home(request):
    #return render(response, "templates/home.html")

def downloadFile(request):   
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    filename='cv_Maria_Vasilache.pdf'
    thefile=base_dir + '/Files/'+ filename
    filename = os.path.basename(thefile)
    chunk_size =8192
    reponse = StreamingHttpResponse(FileWrapper(open(thefile, 'rb'), chunk_size), content_type =mimetypes.guess_type(thefile)[0])
    reponse['Content-Length']=os.path.getsize(thefile)
    reponse['Content-Disposition']="Attachment;filename=%s" % filename
    return reponse

# def pdful(request) 
    pdf.from_file('QR.MyCV.html', 'cv.pdf')   

templates/QR/MyCV.html
{% load static %}

<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ titleCV }}</title>
    <link type="image/x-icon" rel="shortcut icon" href="{% static 'img/cv.ico' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    <link type="text/css" rel="stylesheet" href="{% static 'css/responsive.css' %}">
</head>

<body>
    <div class="p-4">
        <br></br>
        <a href="{% url 'home' %}" class="btn btn-primary btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
    </div> 
    <div class="general__area">
        <div class="top__area">
            <div class="bio__area">
                <div class="photo__area"><img src="{% static 'img/photo3.png' %}" alt="{{ yourName | safe }}" /></div>
                <div class="info__area">
                    <p class="name">{{ yourName }}</p>
                    <p class="profession">{{ yourProfession }}</p>
                    <p class="bio">{{ yourBio }}</p>
                </div>
            </div>
            <div class="personal__area">
                <p class="country">{{ yourCountry }}</p>
                <div class="social__area">
                    {{ yourContact | safe }}
                </div>
                <p class="birth__date">{{ yourBirthday }}</p>
            </div>
            <div class="exp__area">
                {% if yourSkills %}
                <div class="exp__box">
                    <ol aria-label="Skills">
                        {{ yourSkills | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourHobbies %}
                <div class="exp__box">
                    <ol aria-label="Hobbies">
                        {{ yourHobbies | safe }}
                    </ol>
                </div>
                {% endif %}
               
            </div>
        </div>
        <div class="mid__area">
            <div class="status__area">
                {% if yourEdu %}
                <div class="education__area">
                    <ol aria-label="Education">
                        {{ yourEdu | safe }}
                    </ol>
                </div>
                {% endif %}
                {% if yourWork %}
                <div class="work__area">
                    <ol aria-label="Work">
                        {{ yourWork | safe }}
                    </ol>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="bottom__area">
            <div class="history__area">
                {% if yourProject %}
                <div class="project__area">
                    <ol aria-label="Projects">
                        {{ yourProject | safe }}
                    </ol>
                </div>
                {% endif %}
               
            </div>
        </div>
    </div>
    <footer>{{ footerText | safe }}</footer>
    <script type="text/javascript" src="{% static 'js/vanilla-tilt.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/parallax.js' %}"></script>
</body>

</html>

templates/QR/QandA.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
      crossorigin="anonymous"
    />
    <title>Send Email</title>
  </head>
  <body>
    {% comment %} aici modifici sa nu mai ai pagina urata {% endcomment %}
    {% if messageSent %}
    
    <div class="container"><br></br>
      {% comment %} <div class="alert alert-success" role="alert">
        Email successfully sent <a href="#" class="alert-link"></a>
      </div>
     </div> {% endcomment %}
     <div class="p-1">
      <a href="{% url 'home' %}" class="btn btn-success btn-lg" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Enter in your account" tabindex="-1" role="button" aria-disabled="true"><i class="fa fa-home"></i>Home</a>
  </div> 
    <div class="card">
      <div class="card-body">
      
        <p class="card-text"><div class="alert alert-success" role="alert">
          Email successfully sent <a href="#" class="alert-link"></a>
        </div></p>
      
      </div><div class="col-md-4">
      <img src="https://thumbs.dreamstime.com/b/send-us-message-glassy-green-round-button-isolated-abstract-illustration-97495097.jpg" class="card-img-bottom">
    </div>
  </div>

    {% else %}
   
    <div class="card mb-7" style="max-width: 940px;">
      <div class="row g-7">
        <div class="col-md-4">
          <a href="{% url 'home' %}"><img src="https://th.bing.com/th/id/OIP.JFqT7KZtRP-EYjpJVVfqyQHaEU?pid=ImgDet&w=1200&h=700&rs=1" class="img-fluid center"></a>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"> <div class="alert alert-primary" role="alert">
              Send an E-mail about CV issue<a href="#" class="alert-link"></a>
</div></h5>
            <p class="card-text">


              <h1>Contact Us</h1>
              <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}<div class="form-row">
            <div class="form-group col-lg-12 col-md-12 col-sm-12 col-12">
                <label for="attach" class="form-label">Please attach your CV / resume in PDF format</label>
  <input type="file" name="attach" id="attach" onchange="return fileValidation()" accept="application/pdf,application/vnd.ms-excel" class="form-control" required>
            </div>
          </div>
          <div class="form-actions">
            <button type="submit">Send</button>
          </div>
      </form>


            </p>
              </div>
        </div>
      </div>
   
{% comment %}    
    <div class="container">
      <div class="alert alert-primary" role="alert">
                         Send an E-mail about CV issue<a href="#" class="alert-link"></a>
      </div> {% endcomment %}
      
      
      {% comment %} <form method="post">
      
        <input type="hidden" name="csrfmiddlewaretoken" value="vgyNsxCvRbmRfArHBNaJJBYrCsDbF2AZtkmKLZ20rbocnU0dcSZN1uM3IQXfYrLL"> <p><label for="id_recipient">Email:</label> <input type="email" name="recipient" required id="id_recipient"></p>
<p><label for="id_message">Message:</label> <textarea name="message" cols="40" rows="10" required id="id_message">
</textarea></p>


        <br />
        <div class="text-center">
          <input
            type="submit"
            class="btn btn-primary btn-lg"
            style="width: 100%"
            value="Send e-mail"
          />
        </div>
      </form> {% endcomment %}
    </div>
    {% endif %}
  </body>
</html>